services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA_PATH}:/var/lib/postgresql/data

  api:
    restart: unless-stopped
    container_name: ${API_CONTAINER_NAME}
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "5000:5000"
    environment:
      - ENV=${ENV}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./app:/app
    depends_on:
      - db

  nginx:
    restart: unless-stopped
    container_name: ${NGINX_CONTAINER_NAME}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - api
