services:
  redis:
    image: redis:7
    restart: unless-stopped
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    restart: unless-stopped
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA_PATH}:/var/lib/postgresql/data
      - ./db/init_scripts:/docker-entrypoint-initdb.d

  api:
    restart: unless-stopped
    container_name: ${API_CONTAINER_NAME}
    build:
      context: ./flask
      dockerfile: Dockerfile
    expose:
      - "5000:5000"
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      STAKEHOLDERS_EMAILS: ${STAKEHOLDERS_EMAILS}
    volumes:
      - ./flask:/flask
    depends_on:
      - redis
      - db

  celery_worker:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: celery_worker
    restart: unless-stopped
    command: celery -A app.tasks worker --loglevel=info
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      STAKEHOLDERS_EMAILS: ${STAKEHOLDERS_EMAILS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - redis
      - db
      - api

  celery_beat:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: celery_beat
    restart: unless-stopped
    command: celery -A app.tasks beat --loglevel=info
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      STAKEHOLDERS_EMAILS: ${STAKEHOLDERS_EMAILS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - redis
      - db
      - api

  nginx:
    restart: unless-stopped
    container_name: ${NGINX_CONTAINER_NAME}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - api
