name: Integration Test

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Arquivo de teste de integração em tests/integration (ex: test_insights.py)'
        required: true
        default: 'test_insights.py'

jobs:
  pytest-integration:
    name: Integration ▶ ${{ github.event.inputs.test_file }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: |
          mkdir -p reports
          pytest tests/integration/${{ github.event.inputs.test_file }} \
            --maxfail=1 --disable-warnings \
            --junitxml=reports/integration-${{ github.event.inputs.test_file }}.xml

      - name: Upload integration-test report
        uses: actions/upload-artifact@v3
        with:
          name: integration-${{ github.event.inputs.test_file }}.xml
          path: reports/integration-${{ github.event.inputs.test_file }}.xml
