name: CI - Pytest

on:
  repository_dispatch:
    types: [ci-pipeline]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: fake
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      SECRET_KEY: testsecret
      JWT_SECRET_KEY: testjwt
      SQLALCHEMY_DATABASE_URI: sqlite:///:memory:

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Executar Pytest
        run: |
          PYTHONPATH=flask pytest
